services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: foodexpress_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d foodexpress_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --user
      - "${REDIS_USERNAME}"
      - "on"
      - ">${REDIS_PASSWORD}"
      - "~*"
      - "+@all"
      - --user
      - "default"
      - "off"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-u",
          "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@localhost:6379",
          "PING",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:
  redis_data:
